### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by chaitu29495** [RajneeshSingh007/Attendance-App#1]
I did everything as mentioned, but when i click on login, the dialog box appears and its just loading.
Logcat error:

01-24 01:19:04.849 3779-3779/? I/InstantRun: starting instant run server: is main process
01-24 01:19:04.912 3779-3779/com.attendance D/NetworkSecurityConfig: No Network Security Config specified, using platform default
01-24 01:19:05.397 3779-3779/com.attendance W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-24 01:19:05.850 3779-3779/com.attendance D/MainActivity: failed to check login status
01-24 01:19:06.104 3779-3807/com.attendance I/OpenGLRenderer: Initialized EGL, version 1.4
01-24 01:19:06.104 3779-3807/com.attendance D/OpenGLRenderer: Swap behavior 1
01-24 01:19:06.105 3779-3807/com.attendance W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
01-24 01:19:06.105 3779-3807/com.attendance D/OpenGLRenderer: Swap behavior 0
01-24 01:19:06.133 3779-3807/com.attendance D/EGL_emulation: eglCreateContext: 0xa6e05060: maj 3 min 0 rcv 3
01-24 01:19:06.145 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:06.147 3779-3807/com.attendance E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
01-24 01:19:06.147 3779-3807/com.attendance E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
01-24 01:19:06.163 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:09.217 3779-3779/com.attendance I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
01-24 01:19:10.054 3779-3779/com.attendance I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
01-24 01:19:13.173 3779-3779/com.attendance I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
01-24 01:19:14.036 3779-3779/com.attendance W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
01-24 01:19:14.057 3779-3779/com.attendance W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
01-24 01:19:14.074 3779-3779/com.attendance W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-24 01:19:15.785 3779-3779/com.attendance W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-24 01:19:17.066 3779-3779/com.attendance D/Teacher: LoginPage
01-24 01:19:17.153 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:17.182 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:17.193 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:17.218 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:17.304 3779-3807/com.attendance D/EGL_emulation: eglMakeCurrent: 0xa6e05060: ver 3 0 (tinfo 0xa6e03210)
01-24 01:19:18.270 3779-3779/com.attendance D/Login: Failed
01-24 01:19:18.270 3779-3779/com.attendance W/System.err: com.androidnetworking.error.ANError
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:80)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
01-24 01:19:18.270 3779-3779/com.attendance W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by AnoZee** [comment]
Yes, have the same issue as @chaitu29495 
What might be the issue ? @RajneeshSingh007

**Comment by RajneeshSingh007** [comment]
@AnoZee Hello,
Network connectivity is the issue.
Try these steps :
1. copy all php files in xamp/wamp folder
eg: c/wamp/www/attendance/all files.
2. In cmd type ipconfig and note ipv4 address.
3. Run wamp/xampp server.
4. Open project in android studio and in constants(java) file change url address with ip address for eg:
http://192.168.0.2/attendance/login.php
5. Build app and run in the emulator.
6. Local host testing need configuration to run on wireless real device. (for this you could check guides on google to config xamp,wamp).

**Comment by AnoZee** [comment]
Thank you so much.
I'll look into configuring WAMP.
Incase I face any further issues, I'll get back to you.



On 11 Feb 2018 11:22, "Rajneesh Singh" <notifications@github.com> wrote:

@AnoZee <https://github.com/anozee> Hello,
Network connectivity is the issue.
Try these steps :

   1. copy all php files in xamp/wamp folder
   eg: c/wamp/www/attendance/all files.
   2. In cmd type ipconfig and note ipv4 address.
   3. Run wamp/xampp server.
   4. Open project in android studio and in constants(java) file change url
   address with ip address for eg:
   http://192.168.0.2/attendance/login.php
   5. Build app and run in the emulator.
   6. Local host testing need configuration to run on wireless real device.
   (for this you could check guides on google to config xamp,wamp).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RajneeshSingh007/Attendance-App/issues/1#issuecomment-364724224>,
or mute the thread

**Comment by AnoZee** [comment]
I checked the configurations and yet an error persists.
The following attached document is the Logcat file.

**Comment by RajneeshSingh007** [comment]
@AnoZee could you again attach log file...it's not showing.

**Comment by AnoZee** [comment]
Yeah sure

**Comment by rohitsurr** [comment]
I am having the same login issue. I followed all the steps still same.
Is there any solution for this then please help me out.

**Comment by AnoZee** [comment]
I had the same issue and unfortunately it isn't resolved yet.

**Comment by RajneeshSingh007** [comment]
Best Regards,
Rajneesh Singh
http://singhrajneesh.com

**Comment by AnoZee** [comment]
I did follow those steps but no results.
Anyways, I'll retry it.
Thank you.

**Comment by RajneeshSingh007** [comment]
@AnoZee @rohitsurr 
It's connectivity issue.
Please, follow these steps.
1. Start wamp/xamp server
2. Open phpmyadmin in browser
3. Create Demo2 database in phpmyadmin
4. Select Demo2 database and import demo2.sql (available in project folder)
5. Run cmd and type ipcofig (Note : v4 ip address ethernet/lan option) , copy ip address.
6. Open project and change all urls ip address from step 5 in package/misc/constant.java
7. Create directory "attendance" (withour quote) in the c/xamp/htdocs/ or c/wamp/www/
8. Copy all php files in attendance dir(c/xamp/htdocs/attendance/ or c/wamp/www/attendance/).
9.  Open browser, type "localhost/attendance/login.php" (without qoute) 
You'll see required parameters is required.
Then it is okay and working url.
10. Finally build app and run in the emulator.

**Comment by rohitsurr** [comment]
when I am going to localhost/attendance/login.php this error is showing


Warning: mysqli_connect(): (HY000/1049): Unknown database 'demo2' in C:\xampp\htdocs\attendance\Connect.php on line 13

Warning: mysqli_connect(): (HY000/1049): Unknown database 'demo2' in C:\xampp\htdocs\attendance\Connect.php on line 13
{"error":true,"error_msg":"Required parameters is missing!"}



![screenshot 2018-04-17 20 53 40](https://user-images.githubusercontent.com/25316089/38879770-ca049ad4-4281-11e8-8074-21c4b102437a.png)

**Comment by rohitsurr** [comment]
This is the login.php file
![screenshot 2018-04-17 20 59 36](https://user-images.githubusercontent.com/25316089/38880049-688929f4-4282-11e8-8941-7c434727fa43.png)

**Comment by RajneeshSingh007** [comment]
@rohitsurr you created database demo2 in phpmyadmin and imported demo2.sql file ?

**Comment by 8108771098** [comment]
Ok..ty..dont send any more mails pls

**Comment by 8108771098** [comment]
Sir what is username n password for the app ..please tell me

**Comment by AnoZee** [comment]
Check the Database for credentials.
Or create a new user for yourself and login with that.

**Comment by rohitsurr** [comment]
@RajneeshSingh007 yes I created demo2 in phpmyadmin and imported demo2.sql file as you told.

**Comment by rohitsurr** [comment]
The app is running absolutely fine.
The login issue was due to the password at time of login, use 123123 or any other number(first created in phpmyadmin) and it will work as charm.

@RajneeshSingh007 thanks for an awesome project.

**Comment by Babarbwn123** [comment]
@rohitsurr  please send me this running project in which you make changes.
I am waiting, please send me as soon as possible.
This is my final year project, I have to submit it in this month.
babarshabbir2222@gmail.com
send to this mail.

**Comment by rohitsurr** [comment]
@Babarbwn123  no changes are made, the project is fine!

**Comment by rohitsurr** [comment]
@RajneeshSingh007 Can you give some documents or a video explaining the project, that would be really helpful.

**Comment by Richagurav** [comment]
@RajneeshSingh007 we facing problem while logging into an app...it is just processing showing authentication please wait...we have followed all the steps above but still its not helping....sir plz help us....

**Comment by Richagurav** [comment]
@rohitsurr sir plz send your running project where u made all the changes...and plz explain the steps also...tanianaik67@gmail.com

**Comment by rohitsurr** [comment]
No change is required, just use the default password to login first.

**Comment by Richagurav** [comment]
@rohitsurr  sir app is still not working and in login.php page we are getting error like {"error":true,"error_msg":"Required parameters is missing!"}

**Comment by RajneeshSingh007** [comment]
@Richagurav hello, are you checking on localhost with real device?
if yes, please check server connection.

**Comment by Rahulvicky** [comment]
it gets stuck in auth...
it can be improved further a lot ,if you wanna work mail me at rahul56.ka@gmail.com
