### ISSUE TITLE
Error after loading onto a mobile device

### ISSUE THREAD

**Issue by lijopv37** [RajneeshSingh007/Attendance-App#4]
01-01 21:34:41.215 7925-7925/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.attendance, PID: 7925
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/androidnetworking/AndroidNetworking;
                                                     at com.attendance.Attendance.onCreate(Attendance.java:22)
                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6150)
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     at android.os.Looper.loop(Looper.java:197)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7022)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.androidnetworking.AndroidNetworking" on path: DexPathList[[zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/base.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.attendance-Wfct7N5cfGZVBaYXpBlVFw==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

**Comment by RajneeshSingh007** [comment]
Hello,
upgrade AndroidNetworking library.

**Comment by divyanjalicap** [comment]
hy its all done but when in my phone i singin it throws  a message "Authenication" and "Please wait" message ?
